CREATE TABLE temperatures
(
  id INT PRIMARY KEY NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  dateTime DATE UNIQUE,
--   dayofweek DOUBLE,
  minimumtemperature DOUBLE,
  maximumtemperature DOUBLE,
  tempdata DOUBLE
);

CREATE TABLE humiditys
(
  id INT PRIMARY KEY NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  dateTime DATE UNIQUE,
  humidityData DOUBLE
);

CREATE TABLE users(
  id INT PRIMARY KEY NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  name VARCHAR(60),
  password VARCHAR(255),
  status VARCHAR(255)
);